### PR TITLE
feat: Ascii and Unicode

### PR DESCRIPTION
**Pull request by srghma**
add modules similar to https://hackage.haskell.org/package/prettyprinter-1.7.0/docs/Prettyprinter-Symbols-Ascii.html and https://hackage.haskell.org/package/prettyprinter-1.7.0/docs/Prettyprinter-Symbols-Unicode.html

### CODE REVIEW

**Comment by natefaubion** [comment]
Thank you for the PR, but I've deliberately left these out for now. The only reason I've added `Common` at all is mainly for illustrative purposes.

**Comment by srghma** [comment]
what can I say, I kind of understand and kind of not

the `Common` is very useful

do as you want

**Comment by natefaubion** [comment]
I don't want to maintain trivial `text` variations. Everyone has an opinion about what should be there, and you should add this or that, and I just don't want to field those sorts of PRs. The things in `Common` at least implement non-trivial formatting logic, so they truly save time. but `text "("` vs `leftParen` is not saving anyone anything.

**Comment by srghma** [comment]
ok, I am convinced)

**Pull request closed without merging**
